
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Base64;
import java.util.Date;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julia
 */
public final class UserInfo extends javax.swing.JFrame {

    private double totalAmt;
    private SecretKeySpec secretKey;
    private Cipher cipher;
    
    public UserInfo() {
        
        initComponents();
        showDate();
        showTime();
        
        //setting encryption key
        String encryptionKey = "MyEncryptionKey"; // Change this key for more secure encryption
        try {
            byte[] key = encryptionKey.getBytes(StandardCharsets.UTF_8);
            MessageDigest sha = MessageDigest.getInstance("SHA-1");
            key = sha.digest(key);
            key = Arrays.copyOf(key, 16); // AES-128 uses a 16-byte key
             secretKey = new SecretKeySpec(key, "AES");
             cipher = Cipher.getInstance("AES");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error initializing encryption: " + ex.getMessage());
        }
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        lblDate.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(s.format(d));
            }
        }
        ).start();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtM1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtM2 = new javax.swing.JTextField();
        txtM3 = new javax.swing.JTextField();
        txtM4 = new javax.swing.JTextField();
        txtM5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtS1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtS2 = new javax.swing.JTextField();
        txtS3 = new javax.swing.JTextField();
        txtS4 = new javax.swing.JTextField();
        txtS5 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtD1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtD2 = new javax.swing.JTextField();
        txtD3 = new javax.swing.JTextField();
        txtD4 = new javax.swing.JTextField();
        txtD5 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtB1 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtB2 = new javax.swing.JTextField();
        txtB3 = new javax.swing.JTextField();
        txtB4 = new javax.swing.JTextField();
        txtB5 = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblorderNum = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblVat = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MOP = new javax.swing.JComboBox<>();
        lblCash = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lblChange = new javax.swing.JLabel();
        txtChange = new javax.swing.JLabel();
        bttnSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 216, 188));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(247, 241, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Keep on Truckin", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(213, 91, 68));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("La Vie en Rose");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1170, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Keep on Truckin", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 72, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Place Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1170, 40));

        jPanel2.setBackground(new java.awt.Color(225, 141, 131));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Time:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 30));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 235, 240), 3, true));
        jPanel3.setForeground(new java.awt.Color(231, 234, 218));
        jPanel3.setOpaque(false);

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 235, 240), 2, true));
        jPanel8.setOpaque(false);

        jLabel18.setBackground(new java.awt.Color(247, 235, 240));
        jLabel18.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 72, 40));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Main Dishes");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel19.setBackground(new java.awt.Color(247, 235, 240));
        jLabel19.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 239, 239));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("M1");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtM1.setEditable(false);
        txtM1.setBackground(new java.awt.Color(231, 234, 218));
        txtM1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtM1.setForeground(new java.awt.Color(66, 72, 40));
        txtM1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM1.setText("0");
        txtM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM1ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(247, 235, 240));
        jLabel20.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 239, 239));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("M2");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel21.setBackground(new java.awt.Color(247, 235, 240));
        jLabel21.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 239, 239));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("M3");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel22.setBackground(new java.awt.Color(247, 235, 240));
        jLabel22.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 239, 239));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("M4");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel23.setBackground(new java.awt.Color(247, 235, 240));
        jLabel23.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 239, 239));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("M5");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtM2.setEditable(false);
        txtM2.setBackground(new java.awt.Color(231, 234, 218));
        txtM2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtM2.setForeground(new java.awt.Color(66, 72, 40));
        txtM2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM2.setText("0");
        txtM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2ActionPerformed(evt);
            }
        });

        txtM3.setEditable(false);
        txtM3.setBackground(new java.awt.Color(231, 234, 218));
        txtM3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtM3.setForeground(new java.awt.Color(66, 72, 40));
        txtM3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM3.setText("0");
        txtM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3ActionPerformed(evt);
            }
        });

        txtM4.setEditable(false);
        txtM4.setBackground(new java.awt.Color(231, 234, 218));
        txtM4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtM4.setForeground(new java.awt.Color(66, 72, 40));
        txtM4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM4.setText("0");
        txtM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM4ActionPerformed(evt);
            }
        });

        txtM5.setEditable(false);
        txtM5.setBackground(new java.awt.Color(231, 234, 218));
        txtM5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtM5.setForeground(new java.awt.Color(66, 72, 40));
        txtM5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM5.setText("0");
        txtM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel22))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtM5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel17.setBackground(new java.awt.Color(247, 235, 240));
        jLabel17.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(66, 72, 40));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SUMMARY OF ORDERS");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 235, 240), 2, true));
        jPanel15.setOpaque(false);

        jLabel42.setBackground(new java.awt.Color(247, 235, 240));
        jLabel42.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(66, 72, 40));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Sides");
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel43.setBackground(new java.awt.Color(247, 235, 240));
        jLabel43.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 239, 239));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel43.setText(" S1");
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtS1.setEditable(false);
        txtS1.setBackground(new java.awt.Color(231, 234, 218));
        txtS1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtS1.setForeground(new java.awt.Color(66, 72, 40));
        txtS1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS1.setText("0");
        txtS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS1ActionPerformed(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(247, 235, 240));
        jLabel44.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 239, 239));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel44.setText("  S2");
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel45.setBackground(new java.awt.Color(247, 235, 240));
        jLabel45.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 239, 239));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel45.setText(" S3");
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel46.setBackground(new java.awt.Color(247, 235, 240));
        jLabel46.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 239, 239));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel46.setText("  S4");
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel47.setBackground(new java.awt.Color(247, 235, 240));
        jLabel47.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 239, 239));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel47.setText("  S5");
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtS2.setEditable(false);
        txtS2.setBackground(new java.awt.Color(231, 234, 218));
        txtS2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtS2.setForeground(new java.awt.Color(66, 72, 40));
        txtS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS2.setText("0");
        txtS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS2ActionPerformed(evt);
            }
        });

        txtS3.setEditable(false);
        txtS3.setBackground(new java.awt.Color(231, 234, 218));
        txtS3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtS3.setForeground(new java.awt.Color(66, 72, 40));
        txtS3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS3.setText("0");
        txtS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS3ActionPerformed(evt);
            }
        });

        txtS4.setEditable(false);
        txtS4.setBackground(new java.awt.Color(231, 234, 218));
        txtS4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtS4.setForeground(new java.awt.Color(66, 72, 40));
        txtS4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS4.setText("0");
        txtS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS4ActionPerformed(evt);
            }
        });

        txtS5.setEditable(false);
        txtS5.setBackground(new java.awt.Color(231, 234, 218));
        txtS5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtS5.setForeground(new java.awt.Color(66, 72, 40));
        txtS5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS5.setText("0");
        txtS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtS3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel46))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtS1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel44))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtS5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtS2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtS4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtS2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(txtS3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtS4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtS1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtS5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 235, 240), 2, true));
        jPanel16.setOpaque(false);

        jLabel48.setBackground(new java.awt.Color(247, 235, 240));
        jLabel48.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(66, 72, 40));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Desserts");
        jLabel48.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel49.setBackground(new java.awt.Color(247, 235, 240));
        jLabel49.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 239, 239));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel49.setText(" D1");
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtD1.setEditable(false);
        txtD1.setBackground(new java.awt.Color(231, 234, 218));
        txtD1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtD1.setForeground(new java.awt.Color(66, 72, 40));
        txtD1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD1.setText("0");
        txtD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD1ActionPerformed(evt);
            }
        });

        jLabel50.setBackground(new java.awt.Color(247, 235, 240));
        jLabel50.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 239, 239));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel50.setText("D2");
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel51.setBackground(new java.awt.Color(247, 235, 240));
        jLabel51.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 239, 239));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel51.setText(" D3");
        jLabel51.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel52.setBackground(new java.awt.Color(247, 235, 240));
        jLabel52.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 239, 239));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel52.setText("D4");
        jLabel52.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel53.setBackground(new java.awt.Color(247, 235, 240));
        jLabel53.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 239, 239));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel53.setText("D5");
        jLabel53.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtD2.setEditable(false);
        txtD2.setBackground(new java.awt.Color(231, 234, 218));
        txtD2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtD2.setForeground(new java.awt.Color(66, 72, 40));
        txtD2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD2.setText("0");
        txtD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD2ActionPerformed(evt);
            }
        });

        txtD3.setEditable(false);
        txtD3.setBackground(new java.awt.Color(231, 234, 218));
        txtD3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtD3.setForeground(new java.awt.Color(66, 72, 40));
        txtD3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD3.setText("0");
        txtD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD3ActionPerformed(evt);
            }
        });

        txtD4.setEditable(false);
        txtD4.setBackground(new java.awt.Color(231, 234, 218));
        txtD4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtD4.setForeground(new java.awt.Color(66, 72, 40));
        txtD4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD4.setText("0");
        txtD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD4ActionPerformed(evt);
            }
        });

        txtD5.setEditable(false);
        txtD5.setBackground(new java.awt.Color(231, 234, 218));
        txtD5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtD5.setForeground(new java.awt.Color(66, 72, 40));
        txtD5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD5.setText("0");
        txtD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtD3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel52))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtD1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel50))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtD5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtD2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtD4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(txtD2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(txtD3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtD4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtD1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtD5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 235, 240), 2, true));
        jPanel17.setOpaque(false);

        jLabel54.setBackground(new java.awt.Color(247, 235, 240));
        jLabel54.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(66, 72, 40));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Beverages");
        jLabel54.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel55.setBackground(new java.awt.Color(247, 235, 240));
        jLabel55.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 239, 239));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel55.setText(" B1");
        jLabel55.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtB1.setEditable(false);
        txtB1.setBackground(new java.awt.Color(231, 234, 218));
        txtB1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtB1.setForeground(new java.awt.Color(66, 72, 40));
        txtB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB1.setText("0");
        txtB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB1ActionPerformed(evt);
            }
        });

        jLabel56.setBackground(new java.awt.Color(247, 235, 240));
        jLabel56.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 239, 239));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel56.setText("B2");
        jLabel56.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel57.setBackground(new java.awt.Color(247, 235, 240));
        jLabel57.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 239, 239));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel57.setText(" B3");
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel58.setBackground(new java.awt.Color(247, 235, 240));
        jLabel58.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 239, 239));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel58.setText("B4");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel59.setBackground(new java.awt.Color(247, 235, 240));
        jLabel59.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 239, 239));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel59.setText("B5");
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtB2.setEditable(false);
        txtB2.setBackground(new java.awt.Color(231, 234, 218));
        txtB2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtB2.setForeground(new java.awt.Color(66, 72, 40));
        txtB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB2.setText("0");
        txtB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB2ActionPerformed(evt);
            }
        });

        txtB3.setEditable(false);
        txtB3.setBackground(new java.awt.Color(231, 234, 218));
        txtB3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtB3.setForeground(new java.awt.Color(66, 72, 40));
        txtB3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB3.setText("0");
        txtB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB3ActionPerformed(evt);
            }
        });

        txtB4.setEditable(false);
        txtB4.setBackground(new java.awt.Color(231, 234, 218));
        txtB4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtB4.setForeground(new java.awt.Color(66, 72, 40));
        txtB4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB4.setText("0");
        txtB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB4ActionPerformed(evt);
            }
        });

        txtB5.setEditable(false);
        txtB5.setBackground(new java.awt.Color(231, 234, 218));
        txtB5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txtB5.setForeground(new java.awt.Color(66, 72, 40));
        txtB5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB5.setText("0");
        txtB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel58))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel56))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtB4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58)
                            .addComponent(txtB3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtB4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel55)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 560, 390));

        lblTime.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTime.setText("Time");
        lblTime.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 150, 30));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Date:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 30));

        lblDate.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("Date");
        lblDate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, 30));

        jPanel7.setBackground(new java.awt.Color(247, 235, 240));

        jLabel5.setBackground(new java.awt.Color(247, 235, 240));
        jLabel5.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 22, 16));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Name:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtName.setBackground(new java.awt.Color(231, 234, 218));
        txtName.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(66, 72, 40));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(247, 235, 240));
        jLabel12.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(69, 22, 16));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Order Number:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblorderNum.setBackground(new java.awt.Color(247, 235, 240));
        lblorderNum.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblorderNum.setForeground(new java.awt.Color(69, 22, 16));
        lblorderNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblorderNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel13.setBackground(new java.awt.Color(247, 235, 240));
        jLabel13.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(69, 22, 16));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("12% VAT:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblSubTotal.setBackground(new java.awt.Color(247, 235, 240));
        lblSubTotal.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(69, 22, 16));
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubTotal.setText("0000");
        lblSubTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel15.setBackground(new java.awt.Color(247, 235, 240));
        jLabel15.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(69, 22, 16));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Subtotal:");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVat.setBackground(new java.awt.Color(247, 235, 240));
        lblVat.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblVat.setForeground(new java.awt.Color(69, 22, 16));
        lblVat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel16.setBackground(new java.awt.Color(247, 235, 240));
        jLabel16.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(69, 22, 16));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Total Amount:");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblTotal.setBackground(new java.awt.Color(247, 235, 240));
        lblTotal.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(69, 22, 16));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 22, 16));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Mode of Payment:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        MOP.setBackground(new java.awt.Color(231, 234, 218));
        MOP.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        MOP.setForeground(new java.awt.Color(66, 72, 40));
        MOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "E-Cash", "Debit Card", "Credit Card" }));
        MOP.setPreferredSize(new java.awt.Dimension(127, 31));
        MOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOPActionPerformed(evt);
            }
        });

        lblCash.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblCash.setForeground(new java.awt.Color(69, 22, 16));
        lblCash.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCash.setText("Enter Cash:");
        lblCash.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCash.setBackground(new java.awt.Color(231, 234, 218));
        txtCash.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        txtCash.setForeground(new java.awt.Color(66, 72, 40));
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashKeyPressed(evt);
            }
        });

        lblChange.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblChange.setForeground(new java.awt.Color(69, 22, 16));
        lblChange.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblChange.setText("Change:");
        lblChange.setEnabled(false);
        lblChange.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtChange.setBackground(new java.awt.Color(247, 235, 240));
        txtChange.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        txtChange.setForeground(new java.awt.Color(69, 22, 16));
        txtChange.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtChange.setEnabled(false);
        txtChange.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        bttnSave.setBackground(new java.awt.Color(66, 72, 40));
        bttnSave.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        bttnSave.setForeground(new java.awt.Color(231, 234, 218));
        bttnSave.setText("Save & Print Receipt");
        bttnSave.setOpaque(true);
        bttnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MOP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblorderNum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(bttnSave)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblorderNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MOP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 520, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1130, 430));

        jPanel5.setBackground(new java.awt.Color(229, 184, 106));

        jLabelMin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelExit.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setText("x");
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1102, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelExit)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        
        totalAmt = Double.parseDouble(lblTotal.getText());
        double cash  = Double.parseDouble(txtCash.getText());
        
        if(cash > totalAmt){
            lblChange.setEnabled(true);
            txtChange.setEnabled(true);
            double change = cash - totalAmt;
            DecimalFormat df = new DecimalFormat("#.00");
            String strChange = df.format(change);
            txtChange.setText(strChange);
        } else if(totalAmt > cash){
            JOptionPane.showMessageDialog(null, "Invalid cash amount!", "Alert", JOptionPane.WARNING_MESSAGE);
            txtCash.setText(null);
        }
    }//GEN-LAST:event_txtCashActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void txtM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM1ActionPerformed

    private void txtM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2ActionPerformed

    private void txtM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3ActionPerformed

    private void txtM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM4ActionPerformed

    private void txtM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM5ActionPerformed

    private void txtS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS1ActionPerformed

    private void txtS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS2ActionPerformed

    private void txtS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS3ActionPerformed

    private void txtS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS4ActionPerformed

    private void txtS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS5ActionPerformed

    private void txtD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD1ActionPerformed

    private void txtD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD2ActionPerformed

    private void txtD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD3ActionPerformed

    private void txtD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD4ActionPerformed

    private void txtD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD5ActionPerformed

    private void txtB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB1ActionPerformed

    private void txtB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB2ActionPerformed

    private void txtB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB3ActionPerformed

    private void txtB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB4ActionPerformed

    private void txtB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB5ActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        
        
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void MOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOPActionPerformed
        String payment = MOP.getSelectedItem().toString();
        
        if(payment.equals("Cash")){
             txtCash.setEnabled(true);
             lblCash.setEnabled(true);
        } else{
            txtCash.setEnabled(false);
            lblCash.setEnabled(false);
            txtChange.setEnabled(false);
            lblChange.setEnabled(false);
        }
    }//GEN-LAST:event_MOPActionPerformed

    private void txtCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyPressed
 
    }//GEN-LAST:event_txtCashKeyPressed

    private void bttnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSaveActionPerformed
        if(txtName.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Please fill up the name", "Alert", JOptionPane.WARNING_MESSAGE);
        }else if(MOP.getSelectedItem().toString().equals("Cash")){
            if(txtCash.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please enter cash", "Alert", JOptionPane.WARNING_MESSAGE);
            }else{
                saveDataToFile();
            }
        }else{
            saveDataToFile();
        }
        
    }//GEN-LAST:event_bttnSaveActionPerformed

   private void saveDataToFile() {
        String fileName = "ordersData.txt"; // Name of the text file
        
        String cusName = txtName.getText(); 
        String orderNum = lblorderNum.getText();
        String orderDate = lblDate.getText(); 
        String orderTime = lblTime.getText();
        String transacMode = (String)MOP.getSelectedItem(); 
        String total = lblTotal.getText();
        String m1 = txtM1.getText(), m2 = txtM2.getText(), m3 = txtM3.getText(), m4 = txtM4.getText(), m5 = txtM5.getText();
        String s1 = txtS1.getText(), s2 = txtS2.getText(), s3 = txtS3.getText(), s4 = txtS4.getText(), s5 = txtS5.getText();
        String d1 = txtD1.getText(), d2 = txtD2.getText(), d3 = txtD3.getText(), d4 = txtD4.getText(), d5 = txtD5.getText();
        String b1 = txtB1.getText(), b2 = txtB2.getText(), b3 = txtB3.getText(), b4 = txtB4.getText(), b5 = txtB5.getText();

        try {
            FileWriter fileWriter = new FileWriter(fileName, true);
            // Encrypt the data
            try (BufferedWriter bufferedWriter = new BufferedWriter(fileWriter)) {
                // Encrypt the data
                String encryptedData = encrypt(orderNum + "," + cusName + "," + orderDate + "," + orderTime + "," + total + "," + transacMode + "," + m1 + "," + m2 + "," + m3 + "," + m4 + "," + m5 + "," + s1 + "," + s2 + "," + s3 + "," + s4 + "," + s5 + "," + d1 + "," + d2 + "," + d3 + "," + d4 + "," + d5 + "," + b1 + "," + b2 + "," + b3 + "," + b4 + "," + b5 + "," + "Pending");
                // Append the encrypted data to the file
                bufferedWriter.write(encryptedData);
                bufferedWriter.newLine();
                // Close the writer
            }

            JOptionPane.showMessageDialog(this, "Data has been saved to the file.");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error writing to the file: " + ex.getMessage());
        }
        
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.pack();
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }
   
   private String encrypt(String data) {
        try {
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            byte[] encryptedBytes = cipher.doFinal(data.getBytes(StandardCharsets.UTF_8));
            return Base64.getEncoder().encodeToString(encryptedBytes);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error encrypting data: " + ex.getMessage());
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> MOP;
    private javax.swing.JButton bttnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTime;
    public javax.swing.JLabel lblTotal;
    public javax.swing.JLabel lblVat;
    public javax.swing.JLabel lblorderNum;
    public javax.swing.JTextField txtB1;
    public javax.swing.JTextField txtB2;
    public javax.swing.JTextField txtB3;
    public javax.swing.JTextField txtB4;
    public javax.swing.JTextField txtB5;
    private javax.swing.JTextField txtCash;
    private javax.swing.JLabel txtChange;
    public javax.swing.JTextField txtD1;
    public javax.swing.JTextField txtD2;
    public javax.swing.JTextField txtD3;
    public javax.swing.JTextField txtD4;
    public javax.swing.JTextField txtD5;
    public javax.swing.JTextField txtM1;
    public javax.swing.JTextField txtM2;
    public javax.swing.JTextField txtM3;
    public javax.swing.JTextField txtM4;
    public javax.swing.JTextField txtM5;
    private javax.swing.JTextField txtName;
    public javax.swing.JTextField txtS1;
    public javax.swing.JTextField txtS2;
    public javax.swing.JTextField txtS3;
    public javax.swing.JTextField txtS4;
    public javax.swing.JTextField txtS5;
    // End of variables declaration//GEN-END:variables
}
